# Generated by Django 5.1.1 on 2024-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_history_machine_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='machine_name',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
    ]
