# Generated by Django 5.1.1 on 2024-10-09 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_remove_building_short_name_alter_building_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
