# Generated by Django 5.1.1 on 2024-10-10 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_alter_machine_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='notes_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machine',
            name='timer_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
