# Generated by Django 5.1.1 on 2024-10-11 15:50

import django.db.models.deletion
import timer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_alter_machine_notes_date_alter_machine_timer_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['building', 'number']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='building',
            field=models.ForeignKey(default=timer.models.get_default_building, on_delete=django.db.models.deletion.CASCADE, to='timer.building'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.PositiveIntegerField(default=timer.models.get_default_machine_number),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('building', 'number')},
        ),
    ]
