# Generated by Django 5.1.1 on 2024-10-11 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('timer', '0006_alter_machine_options_alter_machine_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('chat_id', models.BigIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.building')),
                ('telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.telegrambot')),
            ],
        ),
    ]
