name: Build, Publish Docker Image, and Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger bei jedem neuen Tag, der mit "v" beginnt, z.B. "v0.0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/laundrytracker:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/laundrytracker:latest

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This release is automatically generated from the new tag.
            Docker image is available under ghcr.io/${{ github.repository_owner }}/laundrytracker:${{ github.ref_name }}
          draft: false
          prerelease: false
